---

- name: Make sure the ambari-agent service is stop
  service:
    name: ambari-agent
    state: stopped

- name: reload systemd
  systemd:
    daemon_reload: yes
   
- name: Set the Ambari Server in the agent configuration
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname="
    line: "hostname={{hostvars[groups['master'][0]].inventory_hostname}}"
    state: present
  
- name: Set the Ambari Server in the agent configuration
  lineinfile:
    path: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^run_as_user="
    line: "run_as_user=ambari"
    state: present    
        
- meta: flush_handlers

- name: Make sure the ambari-agent service is started
  service:
    name: ambari-agent
    state: started

- name: Make sure the ambari-agent service is enabled
  service:
    name: ambari-agent
    enabled: yes
  ignore_errors: true       
   