---

- name: Configure User and set no password for ambari
  hosts: master-worker # all
  become: true
  any_errors_fatal: True
  vars: 
    passwd1: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66333039366266376366633438623837646237383062333861343635393934636566373765326665
          6132323161323439316232306462396465366365666366370a653130346366366264333430336433
          62656563363030336339303538373262633230396530343835356561643831303532656333323531
          3333666430303239660a393138386161393239343163666139636265353564373066383238666639
          3231
    u_mask: "022"
  roles:
    - { role: config, add_user: true, user1: ambari }
    - { role: config, miscellaneous: true, user1: ambari, sudoer: true, adgroup: "", adnetbios: "" }
    - { role: config, miscellaneous: true, user1: root, sudoer: false, adgroup: "", adnetbios: "" }
    #- { role: config, miscellaneous: true, user1: app_admin, sudoer: true, adgroup: "app_group", adnetbios: "TEST007" }
    - { role: config, add_sshkey: true, user1: ambari }  
    - { role: config, add_sshkey: true, user1: root }
    #- { role: config, add_sshkey2: true, user1: app_admin, adnetbios: "TEST007" }
  tags: configure_user ##################

- name: Configure spark1 to httpd/createrepo for yum
  hosts: yum # yum
  become: true
  any_errors_fatal: True
  vars:
    rhel_7:
      - httpd
      - createrepo     
  roles:
    - { role: config, yum: true }
  tags: configure_server ##################

- name: Configure Server All
  hosts: master-worker # all
  become: true
  any_errors_fatal: True
  vars:
    rhel_7:
      - java-1.8.0-openjdk-devel.x86_64
      - dos2unix
      - python-requests 
      - ntp
      - deltarpm    
  roles:
    - { role: config, yum: true }
    - { role: config, selinux: true, reboot: false } # SELINUX NEED REBOOT TO TAKE EFFECT
    - { role: config, misc2: true } 
  tags: configure_server ##################
   
- name: Download ambari yum
  hosts: yum # yum
  become: true
  any_errors_fatal: True  
  vars:
    httpd_path:  /var/www/html/
    artifacts_dest: "/repo/"
    create_dest: true
    artifactslist:
       - { url: 'http://public-repo-1.hortonworks.com/ambari/centos7/2.x/updates/2.7.4.0/', name: 'ambari-2.7.4.0-centos7.tar.gz' }
       - { url: 'http://public-repo-1.hortonworks.com/HDP/centos7/3.x/updates/3.1.4.0/', name: 'HDP-3.1.4.0-centos7-rpm.tar.gz' }
       - { url: 'http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.22/repos/centos7/', name: 'HDP-UTILS-1.1.0.22-centos7.tar.gz' }
    repopathlist:
      - '{{artifacts_dest}}ambari'
      - '{{artifacts_dest}}HDP'
      - '{{artifacts_dest}}HDP-UTILS'
    donotexec: false # true=download       
  roles:
    - { role: ambari , download_repo: true }
    - { role: ambari , createrepo: true }
  tags: ambari_yum ##################

- name: Copy ambari yum to all
  hosts: master-worker # all
  become: true
  any_errors_fatal: True  
  vars:
    hostrepo: "{{groups['yum'][0]}}" 
  roles:
    - { role: config , copyrepo: true }
  tags: ambari_yum ##################

- name: Install Ambari Server Master
  hosts: master # master
  become: true
  any_errors_fatal: True
  vars:
     ambariserverlist:
        - ambari-server
        - ambari-agent
  roles:
    - { role: config, ambari_server: true }
  tags: 
     - ambari_master1 ##################

- name: Install Ambari agent Master-member
  hosts: master-member # master-member
  become: true
  any_errors_fatal: True
  vars:
     ambariserverlist:
        - ambari-agent
  roles:
    - { role: config, ambari_server: true }
  tags: 
     - ambari_master_member ##################

- name: Install Ambari agent
  hosts: worker # worker
  become: true
  any_errors_fatal: True
  vars:
     ambariserverlist:
        - ambari-agent
  roles:
    - { role: config, ambari_server: true }
  tags: 
     - ambari_agent ##################
     
               
- name: Run ambari-agent
  hosts: master-worker # all
  become: true
  any_errors_fatal: True
  roles:
    - { role: ambari, ambari_agent_run: true }
  tags: 
     - ambari_agent_run ##################
            
- name: download jdbc /var/lib/ambari-server oracle
  hosts: master
  become: true
  any_errors_fatal: True
  vars:
    artifacts: ojdbc8.jar
    mode_folder: 0755
    mode_file: 0700
  roles:
    - { role: ambari, ojdbc: true, artifacts_dest: '/var/lib/ambari-server/', owner_folder: ambari, group_folder: root, owner_file: ambari, group_file: root }
    - { role: ambari, ojdbc: true, artifacts_dest: '/usr/share/java/', owner_folder: root, group_folder: root, owner_file: root, group_file: root }
  tags: 
     - download_jdbc_oracle ##################
     
- name: Apply the database role to the ambari-server group
  hosts: sql
  any_errors_fatal: true
  become: yes
  roles:
    - role: database
      #when: database != "embedded" and not database_options.external_hostname|default('')
  tags: database ##################  
        
  
- name: Apply the ambari-server setup for Postgres
  hosts: master
  any_errors_fatal: true
  become: yes
  roles:
    - { role: ambari-server, ambari_setup_postgres: true, when: database == "postgres" }
  tags: 
     - ambari_setup_postgres ##################                        
                             
- name: Run ambari-server for Oracle
  hosts: master
  become: true
  any_errors_fatal: True
  vars:
    user1: AMBARI
  roles:
    - { role: ambari, ambari_server_run: true }
  tags: 
     - ambari_server_run                        

- name: Disable tmp cleanup
  hosts: ambari-member
  become: true
  any_errors_fatal: True
  vars:
    tmp_default: '/usr/lib/tmpfiles.d/tmp.conf'
    tmp_file_path: '/etc/tmpfiles.d/'
    hadoop1log_path: '/hadoop/1/log/'
    user1: ambari
    u_mask: "022" 
    run_master_server: true # false for testing
    run_master_member: true # false for dev  
  roles:
    - { role: config, disable_tmp_cleanup: true }
    #- { role: config, move_log: true }
  tags: 
     - disable_tmp_cleanup
                                                            
- name: after install -copy ambarisudo
  hosts: master-worker # all
  become: true
  any_errors_fatal: True
  roles:
    - { role: config, after_install: true }
  tags: 
     - after_install
                                                            