---

- name: Get disk info and mail it 
  hosts: all 
  any_errors_fatal: True
  vars:
    tmp_folder: /tmp/partition_disk                    
    include_mpath: false
    letters:           # these are the disks like /dev/sdb /dev/sdc
       - b
       - c
       - d
       - e
    raw_prefix: "" 
    path_log:
    log_file:
    filename1: email
    ext: txt    
  roles: 
    - { role: mail_logs, create_log: true, lines: true } 
    - { role: disk, get_raw_disk_prefix: true, become: true, include_mpath: false }
    - { role: disk, get_raw_disk: true, become: true }
    - { role: mail_logs, mail: false } 
  tags: get_raw_disk   
  
- name: Create inventory
  hosts: all 
  vars:
    tmp_folder: /tmp/partition_disk
    fs_name: /opt/tools      # extra vars --file system name -ex /opt/tools or /hadoop
    logical_name: tools # extra vars --logical name like tools --toolsvg --toolslv
    multiple_disk: false  # extra vars --true is designed for /hadoop/1, /hadoop/2 partitioning, false for single partition like dynatrace
                         # meaning multiple disk per server or sing disk per server
    count_disk: 1        # how many disk you want to create on multiple_disk=true
    letters:             # these are the disks like /dev/sdb /dev/sdc 
       - b
       - c
       - d
       - e
    skip_disks:   # extra-vars or survey ex server1sdb or edit the extra-vars ex - server1sde  --it will skop the disk sde on server1
    raw_prefix: "" 
    path_log:
    log_file:
    filename1: email
    ext: txt    
  roles: 
    - { role: mail_logs, create_log: true, lines: false }   
    - { role: disk, get_raw_disk_prefix: true, become: true, include_mpath: false }
    - { role: disk, create_inventory: true, become: true }
    - { role: mail_logs, mail: true, send_mail: false } 
  tags: create_inventory    
    
- name: Create partition   
  hosts: all
  become: true
  any_errors_fatal: True
  vars:
    partition: 1
    include_mpath: false
    skip_disks:   # extra-vars or survey ex server1sdb or edit the extra-vars ex - serversde
    disk_items:
      - { server0: master1, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: 5g } # 21.5
      - { server0: master1, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: 5g } # 21.5
      - { server0: master2, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: 5g } # 21.5
      - { server0: master2, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: 5g } # 21.5
      - { server0: kafka, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: 5g } # 21.5
      - { server0: kafka, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: 5g } # 21.5
      - { server0: spark, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: 5g } # 21.5
      - { server0: spark, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: 5g } # 21.5
  tasks:
    - name: Loop over role
      include_role:
       name: disk
      vars:
        disk_process: DPVLFM   # D=create raw disk P=physical volume V=volumegroup L=logicalvolume F=filesystem M=mount
        create_partition_nolog: true
        server: "{{ item.server0 }}"
        disk1:  "{{ item.disk0 }}"
        pvname: "{{ item.disk0 }}"
        fsname: "{{ item.fsname0 }}"
        vgname: "{{ item.vgname0 }}"
        lvname: "{{ item.lvname0 }}"
        size: "{{ item.size0 }}"
      with_items: 
         - "{{disk_items}}"
  tags: create_partition
  
- name: Check vglv name
  hosts: all 
  vars:
    tmp_folder: /tmp/partition_disk                    
    datestamp: "{{lookup('pipe','date +%Y%m%d')}}"
    letters:     # extra-vars or survey
    skip_disks:   # extra-vars or survey ex server1sdb or edit the extra-vars ex - pddfbcclpfmas02sde
    raw_prefix: "" 
    path_log:
    log_file:
    filename1: email
    ext: txt    
  roles: 
    - { role: mail_logs, create_log: true, lines: true } 
    - { role: disk, check_vglv_name: true }   
    - { role: mail_logs, mail: true } 
  tags: check_vglv_name    
  
- name: Check partition
  hosts: all 
  vars:
    tmp_folder: /tmp/partition_disk                    
    datestamp: "{{lookup('pipe','date +%Y%m%d')}}"
    letters:     # extra-vars or survey
    skip_disks:   # extra-vars or survey ex server1sdb or edit the extra-vars ex - pddfbcclpfmas02sde
    raw_prefix: "" 
    path_log:
    log_file:
    path_2check: '/opt/tools'
    filename1: email
    ext: txt    
  roles: 
    - { role: mail_logs, create_log: true, lines: true } 
    - { role: disk, check_partition: true }   
    - { role: mail_logs, mail: true } 
  tags: check_partition   

- name: Remove partition   
  hosts: all
  become: true
  any_errors_fatal: True
  vars:
    partition: 1
    include_mpath: false
    disk_items:
      - { server0: spark, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: +100%FREE } # 21.5
      - { server0: spark, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: +100%FREE } # 21.5
  tasks:
    - name: Loop over role
      include_role:
       name: disk
      vars:
        disk_process: DPVLFM
        force: yes
        remove_partition_nolog: true
        server: "{{ item.server0 }}"
        disk1:  "{{ item.disk0 }}"
        pvname: "{{ item.disk0 }}"
        fsname: "{{ item.fsname0 }}"
        vgname: "{{ item.vgname0 }}"
        lvname: "{{ item.lvname0 }}" # size is not needed
      with_items: 
         - "{{disk_items}}"
  tags: remove_partition
  
- name: Resize Disk (logical)  
  hosts: all
  become: true
  any_errors_fatal: True
  vars:
    disk_items:
      - { server0: master1, disk0: sdb, fsname0: '/hadoop/1', vgname0: hadoop1vg, lvname0: hadoop1lv, size0: 10g }
      - { server0: master1, disk0: sdc, fsname0: '/hadoop/2', vgname0: hadoop2vg, lvname0: hadoop2lv, size0: 10g }
  tasks:
    - name: Loop over role
      include_role:
       name: disk
      vars:
        resize_logical: true
        server: "{{ item.server0 }}"
        disk1:  "{{ item.disk0 }}"
        pvname: "{{ item.disk0 }}"
        fsname: "{{ item.fsname0 }}"
        vgname: "{{ item.vgname0 }}"
        lvname: "{{ item.lvname0 }}"
        size: "{{ item.size0 }}"
      with_items: 
         - "{{disk_items}}"
  tags: resize_disk  
   