---
  
- include_tasks: selinux.yml
  when: selinux|default(False)==True
  
- include_tasks: yum.yml
  when: yum|default(False)==True     

- include_tasks: copyrepo.yml
  when: copyrepo|default(False)==True     
  
- include_tasks: ambari_server.yml
  when: ambari_server|default(False)==True     

