---
  
- include_tasks: selinux.yml
  when: selinux|default(False)==True
  
- include_tasks: yum.yml
  when: yum|default(False)==True     

- include_tasks: copyrepo.yml
  when: copyrepo|default(False)==True     
  
- include_tasks: ambari_server.yml
  when: ambari_server|default(False)==True     

- include_tasks: add_ip.yml
  when: add_ip|default(False)==True

- include_tasks: add_email.yml
  when: add_email|default(False)==True       
  
- include_tasks: mv_inventory.yml
  when: mv_inventory|default(False)==True     

- include_tasks: add_user.yml
  when: add_user|default(False)==True     

- include_tasks: miscellaneous.yml
  when: miscellaneous|default(False)==True     

- include_tasks: add_sshkey.yml
  when: add_sshkey|default(False)==True

- include_tasks: add_sshkey2.yml
  when: add_sshkey2|default(False)==True   
  
- include_tasks: extract.yml
  when: extract|default(False)==True    

- include_tasks: after_install.yml
  when: after_install|default(False)==True    

- include_tasks: disable_tmp_cleanup.yml
  when: disable_tmp_cleanup|default(False)==True    

- include_tasks: move_log.yml
  when: move_log|default(False)==True    
 
- include_tasks: misc2.yml
  when: misc2|default(False)==True    
    