---

- name: Generate ssh key of {{user1}} on {{ inventory_host }}
  shell: sudo su - {{user1}} -c '[ `hostname` == "{{ item }}" ] && [ ! -f  ~/.ssh/id_rsa ] && ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P "" || mkdir -p ~/.ssh && chmod 0700 ~/.ssh'
  become_user: '{{ user1 }}'
  delegate_to: "{{ item }}"
  loop: "{{ groups.master }}"

- name: Copy public key to ansible 
  fetch: 
    src: ~/.ssh/id_rsa.pub
    dest: ./{{ inventory_hostname }}.id_rsa.pub
    flat: yes
  become_user: '{{user1}}'    
  when: inventory_hostname in groups['master'][0]


- name: Register the ssh keys for each master 
  shell: cat ~/.ssh/id_rsa.pub
  become: true
  become_user: '{{user1}}'
  register: "ssh_keys"
  when: inventory_hostname in groups['master']

- set_fact:
  ssh_keys: "{{ ssh_keys }}"

- name: Add keys to each host for the group
  lineinfile:
    path: ~/.ssh/authorized_keys
    regexp: "{{ inventory_hostname }}"
    state: present
    line: '{{ hostvars[item].ssh_keys.stdout }}'
    owner: "{{user1}}"
    backup: yes
  become_user: '{{user1}}'
  with_items: "{{ groups['master'] }}"
  ignore_errors: true  
