---

- name: Generate ssh key of {{user1}} on {{groups['master'][0]}}
  shell: sudo su - {{user1}} -c '[ `hostname` == "{{groups['master'][0]}}" ] && [ ! -f  ~/.ssh/id_rsa ] && ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -P "" || mkdir -p ~/.ssh && chmod 0700 ~/.ssh'
  
- name: Copy public key to ansible 
  fetch: 
    src: ~/.ssh/id_rsa.pub
    dest: ./id_rsa.pub
    flat: yes
  become_user: '{{user1}}'    
  when: inventory_hostname in groups['master'][0]
     
- name: Copy public key to all
  copy:
    src: ./id_rsa.pub
    dest: ~/.ssh/authorized_keys
    mode: 0644 
    force: no   
  become_user: '{{user1}}'

- name: Copy config to all
  copy:
    src: config
    dest: ~/.ssh/config
    mode: 0400   
    force: no   
  become_user: '{{user1}}'
  
- name: Copy sshkeys of {{groups['master'][0]}} to {{ groups['master-member'][0] }}
  shell: "scp -o ConnectTimeout=5 -o BatchMode=yes ~/.ssh/id_rsa* {{groups['master-member'][0]}}:~/.ssh"
  become_user: '{{user1}}'    
  when: inventory_hostname in groups['master'][0]  
  ignore_errors: true
  
- name: Copy sshkeys of {{groups['master'][0]}} to {{ groups['master-member'][2] }}
  shell: "scp -o ConnectTimeout=5 -o BatchMode=yes ~/.ssh/id_rsa* {{groups['master-member'][1]}}:~/.ssh"
  become_user: '{{user1}}'    
  when: inventory_hostname in groups['master'][0]    
  ignore_errors: true
 